--1
SELECT C.CUSTOMER_NAME, C.CUSTOMER_CITY
FROM CUSTOMER C
LEFT JOIN BORROWER B ON C.CUSTOMER_NAME = B.CUSTOMER_NAME
LEFT JOIN LOAN L ON B.LOAN_NUMBER = L.LOAN_NUMBER
LEFT JOIN ACCOUNT A ON ;

--2 
SELECT C.CUSTOMER_NAME
FROM CUSTOMER C
LEFT JOIN BORROWER B ON C.CUSTOMER_NAME=B.CUSTOMER_NAME
LEFT JOIN LOAN L ON B.LOAN_NUMBER=L.LOAN_NUMBER 
LEFT JOIN 

--3
SELECT M.MONTH, COUNT(A.ACCOUNT_NUMBER)
FROM ACCOUNT A JOIN(SELECT ACCOUNT_NUMBER FROM (SELECT EXTRACT(MONTH FROM ACC_OPENING_DATE)AS MONTH FROM ACCOUNT) M ON A.ACCOUNT_NUMBER=M.ACCOUNT)
GROUP BY M.MONTH;

--7
SELECT BRANCH_NAME,
  CASE
    WHEN BALANCE_SUM > (AVG_BALANCE + 500) THEN ' Elite'
    WHEN BALANCE_SUM >= (AVG_BALANCE - 500) AND BALANCE_SUM <= (AVG_BALANCE + 500) THEN ' Moderate'
    ELSE ' Poor'
  END AS BRANCH_STATUS
FROM (
  SELECT B.BRANCH_NAME, SUM(A.BALANCE) AS BALANCE_SUM, AVG(A.BALANCE) AS AVG_BALANCE
  FROM BRANCH B
  LEFT JOIN ACCOUNT A ON B.BRANCH_NAME = A.BRANCH_NAME
  GROUP BY B.BRANCH_NAME, AVG_BALANCE
);

--9
CREATE TABLE CUSTOMER_NEW 
AS SELECT CUSTOMER_NAME, CUSTOMER_STREET,CUSTOMER_CITY FROM CUSTOMER;

--10
INSERT INTO CUSTOMER_NEW(CUSTOMER_NAME, CUSTOMER_STREET, CUSTOMER_CITY)
SELECT DISTINCT C.CUSTOMER_NAME, C.CUSTOMER_STREET,C.CUSTOMER_CITY
FROM CUSTOMER C
LEFT JOIN DEPOSITOR D ON C.CUSTOMER_NAME = D.CUSTOMER_NAME
LEFT JOIN BORROWER B ON C.CUSTOMER_NAME = B.CUSTOMER_NAME
WHERE D.CUSTOMER_NAME IS NOT NULL OR B.CUSTOMER_NAME IS NOT NULL;
--11
ALTER TABLE CUSTOMER_NEW
ADD STATUS VARCHAR2(15);