CREATE USER dbms_210041203 IDENTIFIED BY cse4308;
GRANT ALL PRIVILEGES TO dbms_210041203;
CONNECT dbms_210041203 / cse4308;
CREATE TABLE ACCOUNT
(
ACCOUNT_NO VARCHAR2(5),
BALANCE NUMBER NOT NULL,
CONSTRAINT PK_ACCOUNT PRIMARY KEY(ACCOUNT_NO)
);
CREATE TABLE CUSTOMER (
    CUSTOMER_NO VARCHAR2(5),
    CUSTOMER_NAME VARCHAR2(20) NOT NULL,
    CUSTOMER_BRANCH VARCHAR2(10),
    CONSTRAINT PK_CUSTOMER PRIMARY KEY(CUSTOMER_NO)
);

ALTER TABLE CUSTOMER DROP PRIMARY KEY;
ALTER TABLE CUSTOMER ADD CONSTRAINT UQ_CUSTOMER UNIQUE (CUSTOMER_NO, CUSTOMER_BRANCH, ROUTING_NO);


CREATE TABLE DEPOSITOR (
    ACCOUNT_NO VARCHAR2(5),
    CUSTOMER_NO VARCHAR2(5),
    CONSTRAINT PK_DEPOSITOR PRIMARY KEY (ACCOUNT_NO, CUSTOMER_NO),
    CONSTRAINT FK_ACCOUNT_NO FOREIGN KEY (ACCOUNT_NO) REFERENCES ACCOUNT(ACCOUNT_NO) ON DELETE CASCADE,
    CONSTRAINT FK_CUSTOMER_NO FOREIGN KEY (CUSTOMER_NO) REFERENCES CUSTOMER(CUSTOMER_NO) ON DELETE CASCADE
);

ALTER TABLE CUSTOMER ADD ROUTING_NO INTEGER;
ALTER TABLE DEPOSITOR ADD (ROUTING_NO INTEGER,CUSTOMER_BRANCH VARCHAR2(10));
ALTER TABLE DEPOSITOR RENAME COLUMN ACCOUNT_NO TO A_NO;
ALTER TABLE DEPOSITOR RENAME COLUMN CUSTOMER_NO TO C_NO;
ALTER TABLE CUSTOMER ADD CONSTRAINT UQ_CUSTOMER UNIQUE (CUSTOMER_NO, CUSTOMER_BRANCH, ROUTING_NO);
ALTER TABLE DEPOSITOR ADD CONSTRAINT FK_DEPOSITOR_ACCOUNT FOREIGN KEY (A_NO) REFERENCES ACCOUNT(ACCOUNT_NO) ON DELETE CASCADE;
ALTER TABLE DEPOSITOR ADD CONSTRAINT FK_DEPOSITOR_CUSTOMER FOREIGN KEY (C_NO, CUSTOMER_BRANCH, ROUTING_NO) REFERENCES CUSTOMER(CUSTOMER_NO, CUSTOMER_BRANCH, ROUTING_NO) ON DELETE CASCADE;


