connect dbms_210041255/cse4308;
SELECT MOV_TITLE FROM MOVIE WHERE MOV_YEAR>=1990 AND MOV_YEAR<=2000;
SELECT ACT_FIRSTNAME FROM ACTOR WHERE ACT_FIRSTNAME LIKE '%a%' AND ACT_FIRSTNAME LIKE '%k';
SELECT DISTINCT A.ACT_FIRSTNAME, A.ACT_LASTNAME FROM ACTOR A, DIRECTOR D WHERE A.ACT_ID = D.DIR_ID;
SELECT A1.ACT_FIRSTNAME, A1.ACT_LASTNAME, A2.ACT_LASTNAME FROM ACTOR A1, ACTOR A2 WHERE A1.ACT_FIRSTNAME = A2.ACT_FIRSTNAME AND A1.ACT_GENDER = 'Female' AND A2.ACT_GENDER = 'Female' AND A1.ACT_ID <> A2.ACT_ID;
SELECT M.MOV_TITLE FROM MOVIE M WHERE M.MOV_ID NOT IN (SELECT DISTINCT MOV_ID FROM RATING);
SELECT AVG(REV_STARS) AS AVERAGE_RATING FROM RATING;
SELECT MOV_COUNTRY, COUNT(*) AS TOTAL_MOVIES FROM MOVIE GROUP BY MOV_COUNTRY;
SELECT M.MOV_TITLE, MinRatings.MIN_RATING
FROM MOVIE M,
(SELECT MOV_ID, MIN(REV_STARS) AS MIN_RATING FROM RATING GROUP BY MOV_ID) AS MinRatings
WHERE M.MOV_ID = MinRatings.MOV_ID
ORDER BY MinRatings.MIN_RATING DESC;
SELECT MOV_TITLE FROM MOVIE M WHERE (SELECT AVG(REV_STARS) FROM RATING R WHERE R.MOV_ID = M.MOV_ID) > (SELECT AVG(REV_STARS) FROM RATING);
SELECT A.ACT_FIRSTNAME, A.ACT_LASTNAME, NUM_RATINGS
FROM ACTOR A,
  (SELECT C.ACT_ID, COUNT(*) AS NUM_RATINGS
   FROM CASTS C
   JOIN RATING R ON C.MOV_ID = R.MOV_ID
   GROUP BY C.ACT_ID) AS ActorRatings
WHERE A.ACT_ID = ActorRatings.ACT_ID;